### ISSUE TITLE
Data for a web GUI to navigate and explore Italian public open data sources

### ISSUE THREAD

**Issue by jenkin** [italia/public-opendata-sources#6]
All informations about sources are scattered in many files with fixed schemas in `orgs/` and `sources/` folders. This is required to maintain the compatibility with CKAN-IT importing and exporting features (see README).

The goal of building a web GUI (ie. embedded in a page of [developers.italia.it](https://developers.italia.it/)) requires a better database schema, so a script (Python3) to transform those files in a single data source for the web page.

This json should be a nested object:

* administration level (ie. "locale" or "nazionale" from the presence or not of `org.region`)
  * regions (ie. values of `org.region`)
    * type of organization (ie. "ministero", "regione", "comune", "università", ... from first words of `org.title`)

An example in pseudo-json syntax:

```
{
    "nazionale": {
        "ministero": [ ... ],
        "altro": [ ... ]
    },
    "locale": {
        "01": {
            "regione": [ ... ],
            "comune": [ ... ],
            "universita": [ ... ],
            "provincia": [ ... ],
            "citta metropolitana": [ ... ],
            "altro": [ ... ]
        },
        "02": {
        },
        ...
    }
}
```

Leaves of this nested object will be an org object with the related sources inside, if present. Join fields are `org.name` and `source.owner_org`.

```
{
    ...org,
    "sources": [
        { ...source },
        ...
    ]
}
```

**Comment by furins** [comment]
Hi Alessio, I'm going to send you a PR with the script. Just a few questions:
1. I think that to identify the organisation in national bodies we should use the first words from org.name and not from org.title because the title may be modified to be human-readable whereas the name should be immutable (since it is also the key for the join between the two datasets) and computer-readable. Is it ok for you?

2. should I write the script in order to take in account for optional command line arguments (orgs and sources paths, output filename) or can we assume that it will be run from the root of the repository folder and output the data to stout / fixed filename? The use case you present seems to have a propensity for the latter, but let me know if you wish a more customisable alternative (e.g. environmental variables?).
thanks in advance
Stefano

**Comment by jenkin** [comment]
Hi Stefano,

1) you are right, please use org.name
2) good point, please use fixed values as defaults of environment variables (name them as you want)

  - input: relative paths of orgs and sources folders
  - output: relative path of json file

Thanks!
